FROM python:3.10-slim

LABEL author=${LABEL}

COPY ./ml_service/app.py .

COPY ./ml_service/fast_api_handler.py .

COPY requirements.txt .

VOLUME /models

RUN pip3 install -r requirements.txt

EXPOSE ${APP_PORT}

CMD uvicorn app:app --reload --port ${APP_PORT} --host 0.0.0.0